services:
  dev:
    container_name: dnn-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ${PWD}/data
        target: /app/data
      - type: bind
        source: ${PWD}/src
        target: /app/src
      - type: bind
        source: ${PWD}/runs
        target: /app/runs
      - type: bind
        source: ${PWD}/experiments
        target: /app/experiments
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    stdin_open: true
    tty: true
    command: tail -f /dev/null