services:
  dev:
    container_name: dnn-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./runs:/app/runs
      - ./experiments:/app/experiments
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    stdin_open: true
    tty: true
    command: tail -f /dev/null
