# path: ~/Develop/dnn_test/src/first/config/basic.yaml
model_params:
  nb_classes: 2
  batch_size: 256
  epochs: 150
  learning_rate: 3e-4

training:
  use_dropout: true
  dropout_rate: 0.2
  use_regularization: false
  use_lr_schedule: true
  lr_patience: 5
  lr_factor: 0.2
  min_lr: 1e-6
  use_batch_norm: false