# path: ~/Develop/dnn_test/src/first/config/regularized_v2.yaml
model_params:
  nb_classes: 2
  batch_size: 128  # 유지 (적절한 크기)
  epochs: 100      # 유지
  learning_rate: 5e-5  # 1e-4 → 5e-5 (더 보수적인 학습)

training:
  use_dropout: true
  dropout_rate: 0.25   # 0.3 → 0.25 (약간 완화)
  use_regularization: true 
  regularization_rate: 5e-5  # 1e-4 → 5e-5 (규제 강도 완화)
  use_lr_schedule: true
  lr_patience: 5       # 3 → 5 (더 여유있는 관찰)
  lr_factor: 0.3      # 0.5 → 0.3 (더 적극적인 감소)
  min_lr: 5e-7        # 1e-6 → 5e-7 (최소값 조정)
  use_batch_norm: true
  class_weights: [1.2, 0.8]  # 새로 추가 (Negative 클래스 가중치 증가)